# ------------------------------ #
#
#  DripperS-Core v0.1
#  (c) Minematador , xSrJowi, DripperNW
#
# ------------------------------ #

# Permissions: To use some commands you need to give them some permission
#
#              - ADMINISTRATOR permissions:
#                 - dripperscore.*
#                 - dripperscore.staffmode.*
#                 - dripperscore.staffmode.freeze
#                 - dripperscore.staffmode.vanish
#                 - dripperscore.staffmode.vanish.others
#                 - dripperscore.staffmode.vanishlist
#
#                 NOT IMPLEMENTED
#                 - dripperSCore.Jobs.*
#                 - dripperSCore.Stats.*
#
#             - USER permissions:
#                - dripperscore.fly
#                - dripperscore.fly.others
#                 NOT IMPLEMENTED
#                 - Jobs:
#                 - Stats:
#                 - Jobs:
#
#
#
#
#              Make sure to remove them from the other groups
#
#
#
#              when giving a new permission.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GENERAL PLUGIN SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
lang: en
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# SQL CONNECTION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
sqlConnection : false
#Now the only aviable sqltype is MySql. Time To time we add the h2 type or mongodb type.
sqlType: MySQL
sqlUrl: localhost
sqlPort: 3306
sqlBBDDName: Prueba
sqlUser: root
sqlPass:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# STAFF
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#
#
#
#