# ------------------------------ #
#
#  DripperS-Core v0.1
#  (c) Minematador , xSrJowi, DripperNW
#
# ------------------------------ #

# Permissions: To use some commands you need to give them some permission
#
#              -ADMINISTRATOR permissions:
#                 - dripperSCore.*
#                 - dripperSCore.StaffMode.*
#                 - dripperSCore.
#
#
#
#
#
#              Make sure to remove them from the other groups
#
#
#
#              when giving a new permission.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GENERAL PLUGIN SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#