# ------------------------------ #
#
#  DripperS-Core v0.1
#  (c) Minematador , xSrJowi, DripperNW
#
# ------------------------------ #

# Permissions: To use some commands you need to give them some permission
#
#              - ADMINISTRATOR permissions:
#                 - dripperscore.*
#                 - dripperscore.staffmode.*
#                 - dripperscore.staffmode.freeze
#                 - dripperscore.staffmode.vanish
#                 - dripperscore.staffmode.vanish.others
#                 - dripperscore.staffmode.vanishlist
#
#                 NOT IMPLEMENTED
#                 - dripperSCore.Jobs.*
#                 - dripperSCore.Stats.*
#
#             - USER permissions:
#
#                 NOT IMPLEMENTED
#                 - Jobs:
#                 - Stats:
#                 - Jobs:
#
#
#
#
#              Make sure to remove them from the other groups
#
#
#
#              when giving a new permission.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GENERAL PLUGIN SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
lang: en
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# SQL CONNECTION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
sqlConnection : false
sqlType: MySQL
sqlUrl: localhost
sqlBBDDName: Prueba
sqlUser: root
sqlPass:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# STAFF
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#
#
#
#