# ------------------------------ #
#
#  DripperS-Core v0.1
#  (c) Minematador , xSrJowi, DripperNW
#
# ------------------------------ #

# Permissions: To use some commands you need to give them some permission
#
#              - ADMINISTRATOR permissions:
#                 - dripperscore.*
#                 - dripperscore.staffmode.*
#                 - dripperscore.staffmode.freeze
#                 - dripperscore.staffmode.vanish
#                 - dripperscore.staffmode.vanish.others
#                 - dripperscore.staffmode.vanishlist
#                 - dripperSCore.Jobs.*
#                 - dripperSCore.Stats.*
#
#             - USER permissions:
#
#                 - Jobs:
#                 - Stats:
#                 - Jobs:
#
#
#
#
#              Make sure to remove them from the other groups
#
#
#
#              when giving a new permission.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GENERAL PLUGIN SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
notPermissonsText: You do noty have the required permission to run this command.
lang: en
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# SQL CONNECTION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
sqlConnection : false
sqlType: MySQL
sqlUrl: localhost
sqlBBDDName: Prueba
sqlUser: root
sqlPass:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# STAFF
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#
# VANISH
PlayerVanishedext: You are invisible to others
PlayerUnVanishedText: You are not invisible to others
#
#
#